// Placeholder data for development and demonstration
// This data is used when the CMS is not configured or for initial preview
// In production, all data comes from the Sanity CMS

import type { Appearance, SiteSettings } from './types'

export const placeholderAppearances: Appearance[] = [
  {
    _id: '1',
    title: 'JanaNayagan Row - SC Order | Nandakumar, Political Analyst on Primetime Newshour',
    youtubeId: 'nm-D1grtQf0',
    channelName: 'Times Now',
    channelUrl: 'https://youtube.com/@TimesNow',
    role: 'guest-analyst',
    topic: 'Legal & Political Affairs',
    description: 'Discussion on the Supreme Court order regarding the JanaNayagan controversy.',
    publishedAt: '2025-12-15',
    featured: true,
  },
  {
    _id: '2',
    title: 'Vijay summoned by CBI | Nandakumar, Political Analyst on CNN-News18 Television',
    youtubeId: '7tm1kUzGC-s',
    channelName: 'CNN-News18',
    channelUrl: 'https://youtube.com/@CNNNews18',
    role: 'guest-analyst',
    topic: 'Political Investigation',
    description: 'Analysis of CBI summons to actor Vijay and its political implications.',
    publishedAt: '2025-12-10',
    featured: true,
  },
  {
    _id: '3',
    title: 'Law & Order in Tamilnadu | Nandakumar Political Analyst',
    youtubeId: 'IAPYUgv20UE',
    channelName: 'News7 Tamil',
    channelUrl: 'https://youtube.com/@News7Tamil',
    role: 'commentary',
    topic: 'Governance & Law',
    description: 'Expert commentary on the law and order situation in Tamil Nadu.',
    publishedAt: '2025-12-05',
    featured: true,
  },
  {
    _id: '4',
    title: 'அண்ணாமலையின் சந்தேகம் அரசியலா? ஆதாரமா? | Annamalai\'s Suspicion - Politics or Evidence?',
    youtubeId: 'aiXUXHFFka0',
    channelName: 'Sathiyam TV',
    channelUrl: 'https://youtube.com/@SathiyamTV',
    role: 'panelist',
    topic: 'BJP Politics',
    description: 'Analysis of BJP leader Annamalai\'s allegations and their political context.',
    publishedAt: '2025-11-28',
    featured: true,
  },
  {
    _id: '5',
    title: 'DMK\'s Double Standard | Nandakumar Political Analyst',
    youtubeId: 'EJ2rmpM3oi0',
    channelName: 'Zee Tamil News',
    channelUrl: 'https://youtube.com/@ZeeTamilNews',
    role: 'guest-analyst',
    topic: 'Party Politics',
    description: 'Critical analysis of DMK\'s policy positions and contradictions.',
    publishedAt: '2025-11-20',
    featured: true,
  },
  {
    _id: '6',
    title: 'பெண்கள் பாதுகாப்பு - உண்மை நிலை என்ன | Women\'s Safety - The Real Situation',
    youtubeId: 'JgBZCCGCDms',
    channelName: 'News7 Tamil',
    channelUrl: 'https://youtube.com/@News7Tamil',
    role: 'commentary',
    topic: 'Women\'s Safety',
    description: 'In-depth analysis of women\'s safety issues and government response.',
    publishedAt: '2025-11-15',
    featured: false,
  },
  {
    _id: '7',
    title: 'சாதிவாரி கணக்கெடுப்பு - சாதி வளர்ப்பா ஒழிப்பா | Caste Census - Growth or Elimination?',
    youtubeId: 'T4I05pqPVxs',
    channelName: 'Zee Tamil News',
    channelUrl: 'https://youtube.com/@ZeeTamilNews',
    role: 'guest-analyst',
    topic: 'Social Policy',
    description: 'Debate on caste census and its implications for social justice.',
    publishedAt: '2025-11-10',
    featured: false,
  },
  {
    _id: '8',
    title: 'சீமான் Vs திருமா அரசியல் | Seeman Vs Thirumavalavan Politics',
    youtubeId: 'oHTxoM5Pc7o',
    channelName: 'Arasiyal Karudan',
    channelUrl: 'https://youtube.com/@ArasiyalKarudan',
    role: 'panelist',
    topic: 'Opposition Politics',
    description: 'Analysis of the political rivalry between Seeman and Thirumavalavan.',
    publishedAt: '2025-11-05',
    featured: false,
  },
  {
    _id: '9',
    title: 'தமிழகத்தில் மீண்டும் ஒரு லாக்கப் மரணமா? | Another Lockup Death in Tamil Nadu?',
    youtubeId: 'wds5UCtPr-Y',
    channelName: 'Nanda Third Eye',
    channelUrl: 'https://youtube.com/@nandathirdeye1152',
    role: 'commentary',
    topic: 'Human Rights',
    description: 'Investigation into custodial deaths and police accountability.',
    publishedAt: '2025-10-28',
    featured: false,
  },
  {
    _id: '10',
    title: 'பீகாரில் 52 லட்சம் வாக்காளர்கள் நீக்கம் - உண்மை என்ன? | Bihar Voter Deletion Truth',
    youtubeId: 'UDJbLrgGu2k',
    channelName: 'Raj News',
    channelUrl: 'https://youtube.com/@RajNews',
    role: 'guest-analyst',
    topic: 'Electoral Issues',
    description: 'Fact-checking claims about voter deletion in Bihar elections.',
    publishedAt: '2025-10-20',
    featured: false,
  },
  {
    _id: '11',
    title: 'SIR முழு விபரங்கள் | Complete Details on SIR',
    youtubeId: 'hMi4KSxV9xA',
    channelName: 'Nanda Third Eye',
    channelUrl: 'https://youtube.com/@nandathirdeye1152',
    role: 'speaker',
    topic: 'Current Affairs',
    description: 'Comprehensive breakdown of the SIR issue and its implications.',
    publishedAt: '2025-10-15',
    featured: false,
  },
  {
    _id: '12',
    title: 'சீமான்+விஜய் சூடு பிடிக்கும் 2026 தேர்தல் களம் | Seeman+Vijay Heating Up 2026 Elections',
    youtubeId: 'cZZIo-Q-eUY',
    channelName: 'Nanda Third Eye',
    channelUrl: 'https://youtube.com/@nandathirdeye1152',
    role: 'commentary',
    topic: 'Election Analysis',
    description: 'Analysis of potential Seeman-Vijay alliance and 2026 election dynamics.',
    publishedAt: '2025-10-10',
    featured: false,
  },
  {
    _id: '13',
    title: 'விஜயால் வீழும் திமுக | DMK\'s Fall Due to Vijay',
    youtubeId: '1LlOR2IaqYk',
    channelName: 'Nanda Third Eye',
    channelUrl: 'https://youtube.com/@nandathirdeye1152',
    role: 'commentary',
    topic: 'Party Politics',
    description: 'Analysis of TVK\'s impact on DMK\'s political prospects.',
    publishedAt: '2025-10-05',
    featured: false,
  },
  {
    _id: '14',
    title: 'Supreme Court Vs Parliament',
    youtubeId: 'iCMQulWSqP0',
    channelName: 'Nanda Third Eye',
    channelUrl: 'https://youtube.com/@nandathirdeye1152',
    role: 'speaker',
    topic: 'Constitutional Affairs',
    description: 'Analysis of the ongoing tension between judiciary and legislature.',
    publishedAt: '2025-09-28',
    featured: false,
  },
  {
    _id: '15',
    title: 'India - The Most Favoured Nation',
    youtubeId: 'KqTKIb0z0C0',
    channelName: 'Nanda Third Eye',
    channelUrl: 'https://youtube.com/@nandathirdeye1152',
    role: 'speaker',
    topic: 'Geopolitics',
    description: 'Analysis of India\'s growing international stature and diplomatic relations.',
    publishedAt: '2025-09-20',
    featured: false,
  },
  {
    _id: '16',
    title: 'திமுகவின் நீட் எதிர்ப்பு ரகசியம் | DMK\'s NEET Opposition Secret',
    youtubeId: 'odkVtKIdB4Q',
    channelName: 'Nanda Third Eye',
    channelUrl: 'https://youtube.com/@nandathirdeye1152',
    role: 'commentary',
    topic: 'Education Policy',
    description: 'Investigating the political motivations behind DMK\'s anti-NEET stance.',
    publishedAt: '2025-09-15',
    featured: false,
  },
  {
    _id: '17',
    title: 'மூன்றே நிமிடத்தில் National Herald Case | National Herald Case in 3 Minutes',
    youtubeId: 'yc1irQOUbpw',
    channelName: 'Nanda Third Eye',
    channelUrl: 'https://youtube.com/@nandathirdeye1152',
    role: 'speaker',
    topic: 'Legal Affairs',
    description: 'Quick explainer on the National Herald case and its political significance.',
    publishedAt: '2025-09-10',
    featured: false,
  },
  {
    _id: '18',
    title: 'Air India Flight - Take off to Crash',
    youtubeId: 'PmkibtX0LcY',
    channelName: 'Nanda Third Eye',
    channelUrl: 'https://youtube.com/@nandathirdeye1152',
    role: 'speaker',
    topic: 'Aviation & Policy',
    description: 'Analysis of Air India\'s journey and aviation policy implications.',
    publishedAt: '2025-09-05',
    featured: false,
  },
]

export const placeholderSettings: SiteSettings = {
  name: 'Nandakumar K',
  title: 'Political Analyst, Strategic Advisor & Business Consultant',
  tagline: 'A management consultant with expertise in strategy development, solving complex business problems, operational efficiency, and business transformation. Providing expert political analysis on elections, policy, and governance while partnering with organizations to identify challenges, design actionable solutions, and deliver measurable results.',
  email: 'contact@nandakumark.com',
  aboutShort: 'A Post Graduate in Mathematics & Business Administration with 30 years of in-depth knowledge and experience across diverse industries including Food Additives, Feed Additives, Animal Feeds, Veterinary Pharmaceuticals, and Financial Services. Passionate about solving complex problems, enabling sustainable growth, building high-performance teams, and now bringing this analytical rigor to political commentary and strategic advisory.',
  expertise: [
    'Political Analysis & Electoral Commentary',
    'Strategy Development & Business Transformation',
    'Operational Efficiency & Process Optimization',
    'Leadership Team Advisory',
    'Data-Driven Decision Making',
    'Sales & Business Development',
    'Team Building & Training',
    'Policy Research & Governance Analysis',
  ],
  credentials: [
    {
      title: 'Political Analyst & Strategic Advisor',
      organization: 'Independent Practice',
      period: '2025 - Present',
      description: 'Full-time political analyst providing electoral commentary, strategic advisory to political organizations, and business consulting services. Regular media appearances across major news networks including Times Now, CNN-News18, News7 Tamil, Zee Tamil, and Sathiyam TV.',
    },
    {
      title: 'General Manager',
      organization: 'Kemin Industries',
      period: '2016 - 2025',
      description: 'Led business operations and strategic initiatives at a global ingredient manufacturer. Drove growth, optimized processes, and helped leadership teams make data-driven decisions across South Asia markets.',
    },
    {
      title: 'Regional Director',
      organization: 'Kemin Industries South Asia Pvt Ltd.',
      period: '2020 - 2025',
      description: 'Oversaw regional operations across South Asia, managing cross-functional teams and driving business expansion in the food and feed additives sector. Chennai, Tamil Nadu.',
    },
    {
      title: 'Business Manager & National Sales Manager',
      organization: 'Kemin Industries',
      period: '2011 - 2015',
      description: 'Progressive leadership roles driving national sales strategy, business development, and market expansion. Built and managed high-performing sales teams across India.',
    },
    {
      title: 'Senior Branch Manager',
      organization: 'ING Life (now HDFC Life)',
      period: '2009 - 2011',
      description: 'Managed a team of 13 Sales Managers, 4 Financial Consultants, and 550 Advisors. Led recruiting, training, and performance management for the Coimbatore-Tirupur region in financial services.',
    },
    {
      title: 'Regional Business Manager',
      organization: 'Ayurvet Limited',
      period: '2006 - 2009',
      description: 'Responsible for MIS, event management, sales, and profit management in the veterinary pharmaceuticals sector. Built foundational expertise in agricultural and animal health industries.',
    },
  ],
  socialLinks: {
    twitter: 'https://twitter.com/nandakumark',
    linkedin: 'https://linkedin.com/in/nandakumar-kathirvel-55613056',
  },
}
